### PR TITLE
Fix forwarding props to TileLayer

### LINKED ISSUE #36: Tile Flickering
There's currently some tile flickering:

Screen Recording 2020-05-01 at 6 30 36 PM

Upon closer inspection, I can see that the `refinementStrategy` prop isn't actually being passed through correctly.

It's set on the `EarthEngineLayer` here in the example:
https://github.com/UnfoldedInc/earthengine-layers/blob/1d4e3863c7caec774473c13dfad0ae3fcc11624b/examples/ee-demo/app.js#L78

But that prop isn't being set correctly on the `TileLayer` here:
https://github.com/UnfoldedInc/earthengine-layers/blob/1d4e3863c7caec774473c13dfad0ae3fcc11624b/modules/earthengine-layers/src/earth-engine-layer.js#L106-L135

But looking at the _component state of the `TileLayer`_, `refinementStrategy` isn't set, 
image

### PR DESCRIPTION
**Pull request by kylebarron**
Forwards all props passed to `EarthEngineLayer` down to `TileLayer`. Closes #36 

- Do I need to use `Object.assign` instead of spreading `...this.props`?
- There's still a little bit of "flicker" with alternative `refinementStrategy` methods. For now I have the `ee-demo` example set to `refinementStrategy: 'no-overlap'`.

	`refinementStrategy: 'no-overlap'`: Some empty tiles when loading at a new zoom
	Screen Recording 2020-05-04 at 3 52 00 PM

	`refinementStrategy: 'never'`: At every zoom threshold, the entire map is white while tiles load.
	Screen Recording 2020-05-04 at 3 56 04 PM

### CODE REVIEW

**Comment by kylebarron** [comment]
The [`CompositeLayer` docs](https://deck.gl/#/documentation/developer-guide/writing-custom-layers/composite-layers?section=forwarding-properties) write out every possible prop individually. Is that preferable to passing all of them down? Passing all of them down would also allow a `BitmapLayer` prop to be passed to `EarthEngineLayer`

File: examples/ee-demo/app.js [hunk 1]
```diff
@@ -73,9 +73,9 @@ export default class App extends React.Component {
         eeObject: this.state.eeImage,
         visParams: {min: 0, max: 255},
         opacity: 0.5,
-        // Do not display any tile that is not selected
+        // Prevent overlapping tiles from multiple zoom levels
         // https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer?section=refinementstrategy-enum-optional-
-        refinementStrategy: 'never'
+        refinementStrategy: 'no-overlap'
```
Comment (ibgreen) [inline examples/ee-demo/app.js:78]: It is worth asking whether this should even be exposed. Not against it, but given the issues with opacity I am not sure the alternative is worth the potential confusion.

Comment (kylebarron) [reply examples/ee-demo/app.js:78]: I would be in favor of a default like `no-overlap`, but include in the documentation that all `TileLayer` props are inherited, so if a user had a reason for forcing an alternative strategy they could override it.

Comment (kylebarron) [reply examples/ee-demo/app.js]: I took this out of here and set `no-overlap` in `defaultProps`

**Comment by kylebarron** [comment]
I updated to be explicit about forwarded props `TileLayer`. But it looks like some non-`TileLayer` props are still getting passed, for example `opacity`. In the `opacity` case, we want it to be passed down, but that might indicate all props are still getting passed?

**Comment by kylebarron** [comment]
The `TerrainLayer`, another `CompositeLayer` [does this](https://github.com/visgl/deck.gl/blob/554dec0ab8c5c7d07acb0ae752c0f9d6994b2cc4/modules/geo-layers/src/terrain-layer/terrain-layer.js#L190-L223):
```jsx
  renderLayers() {
    const {
      color,
      material,
      elevationData,
      texture,
      wireframe,
      meshMaxError,
      elevationDecoder
    } = this.props;

    if (this.state.isTiled) {
      return new TileLayer(
        this.getSubLayerProps({
          id: 'tiles'
        }),
        {
          wireframe,
          color,
          material,
          getTileData: this.getTiledTerrainData.bind(this),
          renderSubLayers: this.renderSubLayers.bind(this),
          updateTriggers: {
            getTileData: {
              elevationData: urlTemplateToUpdateTrigger(elevationData),
              texture: urlTemplateToUpdateTrigger(texture),
              meshMaxError,
              elevationDecoder
            }
          },
          onViewportLoad: this.onViewportLoad.bind(this),
          zRange: this.state.zRange || null
        }
      );
    }
```

I suppose I should insert custom props outside of `this.getSubLayerProps`

**Comment by ibgreen** [comment]
> I updated to be explicit about forwarded props TileLayer. But it looks like some non-TileLayer props are still getting passed, for example opacity. In the opacity case, we want it to be passed down, but that might indicate all props are still getting passed?

`getSubLayerProps` forwards the basic layer props such as opacity modelMatrix etc, plus any additional props you specify.

**Comment by ibgreen** [comment]
> I suppose I should insert custom props outside of this.getSubLayerProps

why not add them as part of the props object you pass into that call?

**Comment by kylebarron** [comment]
> why not add them as part of the props object you pass into that call?

Just because the `TerrainLayer` example puts them outside of `getSubLayerProps`. I suppose it doesn't really matter?
